### ISSUE TITLE
Tip Calculation Based on Service Rating

### ISSUE THREAD

**Issue by Sahilwagh03** [Sahilwagh03/smart-_tipper#1]
The current system requires manual tip percentage input. Introducing a feature where users can select from service rating options (e.g., "Below Average," "Satisfactory," "Great," "Outstanding") would streamline the process. Each rating would correspond to a predefined tip percentage, making tipping faster and more intuitive for users.

**Comment by sudarshandongre** [comment]
I have implemented a feature that allows users to select from predefined service rating options ("Below Average," "Satisfactory," "Great," "Outstanding") instead of manually inputting the tip percentage. Each rating now corresponds to a predefined tip percentage, streamlining the tipping process and making it more intuitive and faster for users.
 
![WhatsApp Image 2024-09-20 at 18 37 15 (1)](https://github.com/user-attachments/assets/53452fe6-e9e9-443b-b16b-ca2533226f74)
